### ISSUE TITLE
Spatial dynamic filters

### ISSUE THREAD

**Issue by 13331112522** [wenz116/lang2seg#3]
There should be 7 filters as you mentioned in the paper,  including up, down, left, right, horizontal and vertical middle regions, and each region covers a half area of the entire image. I have not see 7 spatial awared filters in your joint-match.py, but only one dynamic filters based on language input, dynamic.fc. Where can I find them?

**Comment by wenz116** [comment]
You can find the 7 dynamic filters in [resnet_v1_7f_response.py](https://github.com/wenz116/lang2seg/blob/master/pyutils/mask-faster-rcnn/lib/nets/resnet_v1_7f_response.py#L306) and [network_7f_response.py](https://github.com/wenz116/lang2seg/blob/master/pyutils/mask-faster-rcnn/lib/nets/network_7f_response.py#L483) if you run the 4th option in Training, or in [resnet_v1_cycle_response.py](https://github.com/wenz116/lang2seg/blob/master/pyutils/mask-faster-rcnn/lib/nets/resnet_v1_cycle_response.py#L312) and [network_cycle_response.py](https://github.com/wenz116/lang2seg/blob/master/pyutils/mask-faster-rcnn/lib/nets/network_cycle_response.py#L509) if you run the 5th option in Training.

joint_match.py is not used in my final version of code. You can ignore this file.
